### ISSUE TITLE
Sporadic Sign in Issues

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#196]
Leaders with login info are able to login without issues at times and unable to login at others. There doesn't seem to be a rhyme or reason.

**Comment by jeffklassen** [comment]
What are the issues they are having? What is a username who is having
trouble?

On Jun 11, 2017 4:51 PM, "amandawmosaic" <notifications@github.com> wrote:

Leaders with login info are able to login without issues at times and
unable to login at others. There doesn't seem to be a rhyme or reason.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MosaicGroups/mosaic-groups/issues/196>, or mute the
thread

**Comment by amandawmosaic** [comment]
Jess Coleman had issues yesterday. I don't know what her password is, but the username is jessica@mosaicchristian.org.

**Comment by jeffklassen** [comment]
@amandawmosaic I'm having trouble re-creating this problem and I need to be able to recreate it before I can fix it.

Are users able to login after login fails for the first time? 
Are users still reporting this error?
What error were they seeing?

Would you please try to get the following information next time a user has trouble logging in?

- Username,
- Browser type (chrome, safari, etc.) and version
- as close to the exact time as possible that the user tried to log in but failed?

Also would you help me understand the problem

**Comment by amandawmosaic** [comment]
No one has reported an issue in the last few days so if it occurs again I'll be sure to have Jess send this info your way as I'll be out of the country starting Friday.
