### ISSUE TITLE
URGENT: The website is down again

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#199]
We've tried opening it on multiple devices and on multiple browsers and we just get a white screen. No error, no nothing. 

Sign ups will be occurring over the next two weeks. What can I do to help make this go more smoothly?

**Comment by jeffklassen** [comment]
It looks like its back up now. Digging to see what happened.

**Comment by jeffklassen** [comment]
It looks like it was automatically restarted after it went down. If this happens again, would you please provide a screen shot of what it looks like when its down?

I've also signed us up for 'uptimerobot'. I am a little skeptical of this product as it only does high level check of the website, rather than something a bit more in depth. However uptimerobot is free - the next step up costs ~$7/month. If uptimerobot does not do what we want it to, I suggest we move to uptimerobot.
