### ISSUE TITLE
Archive Past Group Information

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#64]
If this could be accomplished as soon as possible that would be great as we'd like to have people inputting new groups starting next week.

**Comment by jeffklassen** [comment]
@amandawmosaic and @BKreisel This is going to require a fix that will take more than a week to implement. I think we need to figure out a work around for now so that we can save off (in a flat file?) the current groups data so that we can reinsert it later as archived.

I'm suggesting that we continue with the current workflow for this next round of groups where we delete all the existing groups, and insert new ones. However, before we do the delete, I think we save off the existing data. We can work to reupload this later.

**Comment by jeffklassen** [comment]
@amandawmosaic Does the above sound reasonable to you?

Additionally - I need you to help me walk through what the 'archival' workflow looks like. Here's my first stab at it:

1. When a semester ends, an Admin logs in and selects to 'Archive All'. This will archive all active groups.
2. Then leaders can start entering new groups.

How do people 'unarchive' groups if groups were accidentally archived?

Looking forward to your feedback! This represents a big change to the app -- lets take the time to get this right!

**Comment by amandawmosaic** [comment]
Workflow looks great. 

Could someone one go into the archives and simply copy and paste a group's description, and retreat a new group. I would be the only one doing that, as the only group I can think of that would need "unarchiving" are the student groups that repeat every semester.

We wouldn't allow anyone to create a new group until the old ones were fully archived. What do you think?

**Comment by amandawmosaic** [comment]
Let me know when the information has been saved, so that we can being entering new groups

**Comment by jeffklassen** [comment]
@amandawmosaic I'd like to tweak workflow above slightly. Instead of marking all groups as 'archived', I think you should go in and 

1. elect to 'Start a new semester, enter name here:' `Fall 2019`.
2. This will hide (effectively archive) all groups from previous semesters (ie, Summer 2019, Spring, 2019, Fall 2018, etc.). 
3. Once you've started a new semester, all groups added will be added under that semester
4. Only groups from the currently active semester will be displayed on the website
5. Eventually (we will log a separate ticket for this), admins will be able to view groups from previous semesters.

Does that make since? I think this is a much better solution.

**Comment by amandawmosaic** [comment]
Yep- makes sense

**Comment by jeffklassen** [comment]
Closed!
